name: docker-ci

on: 
  push:
    branches:
      - dev
      - main
      - master
    tags:
      - v*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
             
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
      - name: Add TAG_VERSION env property with tag version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TAG_VERSION=`echo ${GITHUB_REF} | cut -c11-`" >> $GITHUB_ENV
           
             
      - name: Build and push ams docker image
        env:
          DOCKER_IMAGE_AMS: imenco/antmediaserver:${{ env.SHORT_SHA }}
        run: make build-push-docker

      - name: Build and push ams docker image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          DOCKER_IMAGE_AMS: imenco/antmediaserver:${{ env.TAG_VERSION }}
        run: make build-push-docker